### PR TITLE
Left/Right navigation between pause button and toggle 

### PR DESCRIPTION
**Pull request by AkazaRenn**
<del>The logic is ready, it's just the design that needs to be re-done since we have gotten rid of ToggleField. Just to let you know that it's there and you can give it a test if you wish.</del>

<del>I'll change it to in review once it's finished.</del>

Seems good now, do you mind giving it a try?
Screenshot 2024-07-13 212549
It should look the same as before.

### CODE REVIEW

**Comment by AkazaRenn** [comment]
If you got time, can you please take a look on how to style this thing? It's quite crazy how a long-name game can push everything out of border. I'm quite lost on it.

**Comment by AkazaRenn** [comment]
Screenshot 2024-07-13 201452
This is how the problem looks like, it's a free game so you can test with it as well https://store.steampowered.com/app/2167960/__Buy_a_Croquette/

It's making me feel despair TBH, not sure how this thing can be styled.

**Comment by AkazaRenn** [comment]
Seems good now, do you mind giving it a try?
Screenshot 2024-07-13 212549
It should look the same as before.

**Comment by wynn1212** [comment]
This pull request looks good to me, and the navigation works as intended. I have tested it with 5 games and 2 applications, and it works very well. However, I encountered some issues during testing.
- There's a known issue where non-Steam games get paused on startup and need to be manually unpaused. (https://github.com/wynn1212/SDH-PauseGames/pull/2#issuecomment-2214389447) If the user pauses the current running Steam game and then unpauses a non-Steam game, due to how the Pause Games logic works, when the user decides to switch back to the Steam game, they will find that the non-Steam game is still running in the background and not paused, while the Steam game remains paused. This requires manually pausing the non-Steam game and unpausing the Steam game. After this operation, everything works normally again (switching between Steam and non-Steam games no longer requires manual pause/unpause).

**Review by wynn1212 — APPROVED** [review]
LGTM

**Comment by wynn1212** [comment]
As for the known issue about non-Steam games pausing/resuming, if you have any ideas on how to fix this, feel free to submit a new pull request. I am merging this request for now.

Also, if you think your improvement is ready, we can ask @popsUlfr to take over and continue this project.

**Comment by AkazaRenn** [comment]
@wynn1212 for the pause problem I think it's beyond the scope of this plugin to do any fix and I don't want to implement a dirty workaround just to repair something that should have happened in the beginning. Please feel free to reach out to the original author for the project take over.

**Comment by wynn1212** [comment]
Hi @AkazaRenn ,

Sorry for the late reply. By the way, would you like to be the leader of this new project or be added as a collaborator? You've contributed a lot to fixing the previous issues.

**Comment by AkazaRenn** [comment]
@wynn1212 I didn't think about it actually 🫠 it's fine for me to take ownership if you wish, but I'm also ok to keep the current situation. It's up to you I guess, but wo don't need to decide it right now, still get some time before the original developer responds.

**Comment by wynn1212** [comment]
@AkazaRenn Sure thing, let's keep the current situation for now since I have already submitted this plugin update before, which should help with a quicker acceptance.

Additionally, we can consider bumping the version to 0.5.0 (or 1.0.0 once Decky Loader 3.0.0 with the new Decky API becomes stable) since we have resolved most of the issues from the original developer.

**Comment by AkazaRenn** [comment]
@wynn1212 I was using 0.5.0 for my change, but 1.0.0 feels a good option as well, it's up to you.

**Comment by AkazaRenn** [comment]
Hi @wynn1212, since the original developer hasn't responded for quite a while, it seems unlikely we can get the permission to takeover this plugin. Due to that, I'm wondering if you would like to release this fork to the store? We can use a new name maybe "GamePause" or anything you find appropriate.

**Comment by wynn1212** [comment]
Good questions, @AkazaRenn! I was planning to discuss this as well. I'm going to leave another message on your pull request in the original developer's plugin repository (hopefully, he/she will notice). If we still don’t get a response from the original developer, we could consider reaching out to the Decky Loader team regarding this situation and inquire if we can take over the project. Given that there's a "plugin-maintainership" label in the Decky Plugin Database and previous cases of project takeovers, it seems possible if the original developer remains unavailable.

If that's not an option, we can decide to publish the plugin under a new name. But I think reaching out to the Decky Loader team is worth trying since it's been done before.

Also, since Decky V3 has become stable, do you think it’s feasible to migrate our plugin to Decky V3? If so, we could be ready to release version 1.0.0 once the project takeover issue is resolved.

**Comment by AkazaRenn** [comment]
Sounds goods, I'll make a PR for v3 migration soon.

**Comment by wynn1212** [comment]
Great! I’ve left a message on your pull request on the original developer’s plugin GitHub. Now, I’m going to update some documentation regarding the non-Steam pause issue.

**Pull request merged**
