### PR TITLE
Document update, merge pause button with game icon

### PR DESCRIPTION
**Pull request by AkazaRenn**
This is to address the comments you shared in the previous PR. As for the issue about non-Steam games, I can confirm that and am thinking about how it can be fixed right now, my current plan is to still let it get paused (since it's started in background) but make it possible to resume when switched to it.

Do you mind giving it a test? I'm not sure if my own tests can cover all the scenarios. Thanks!

### CODE REVIEW

**Comment by AkazaRenn** [comment]
The button seems still not working... It may not be a size issue, let me check again.

**Comment by AkazaRenn** [comment]
image
here's how it looks like now

**Comment by wynn1212** [comment]
Hi there,

This pull request looks good to me, and after testing on my SD OLED, the pause/play button works via touch and cursor.

And here is some suggestion about this pull request:
- **Control Direction Enhancement:** When there are multiple games in the paused game list, pressing the down key should navigate to the next game instead of moving right to the toggle switch. This would make navigation more intuitive.

As for issue about non-steam games, the possible cause might be when non-Steam games are not fully launched. The `focusedApp` variable might not get the full information, requiring manual unpausing. 
- https://github.com/wynn1212/SDH-PauseGames/blob/d841396ee573deed7cd7b6da5cb09f9b43d8eea4/src/backend.ts#L90-L95

Here's some information found during discovery
- Non-steam games launched (firefox) with pause on focus loss enabled, and automatically got paused by pause games
```
(deck@SDOLED1T ~)$ ps aux | grep firefox
deck       12178  0.5  0.0  28108  5632 ?        S    22:12   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3041142249 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /usr/bin/flatpak run --branch=stable --arch=x86_64 --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 --env=WAYLAND_DISPLAY=wayland-0 --env=MOZ_USE_XINPUT2=1 --command=firefox --file-forwarding org.mozilla.firefox -p deck @@u @@
deck       12184  0.2  0.0   2860  1920 ?        T    22:12   0:00 bwrap --args 64 -- firefox -p deck
deck       12201  0.1  0.0   2860  1160 ?        T    22:12   0:00 bwrap --args 64 -- firefox -p deck
deck       12208  0.1  0.2 2418460 38528 ?       Tl   22:12   0:00 /app/lib/firefox/firefox --name org.mozilla.firefox -p deck
deck       12358  0.0  0.0   6500  2428 pts/1    S+   22:13   0:00 grep --color=auto firefox
(deck@SDOLED1T ~)$
```
- After manually unpause non-steam games (firefox)
```
(deck@SDOLED1T ~)$ ps aux | grep firefox
deck       12178  0.1  0.0  28108  5632 ?        S    22:12   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3041142249 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /usr/bin/flatpak run --branch=stable --arch=x86_64 --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 --env=WAYLAND_DISPLAY=wayland-0 --env=MOZ_USE_XINPUT2=1 --command=firefox --file-forwarding org.mozilla.firefox -p deck @@u @@
deck       12184  0.0  0.0   2860  1920 ?        S    22:12   0:00 bwrap --args 64 -- firefox -p deck
deck       12201  0.0  0.0   2860  1160 ?        S    22:12   0:00 bwrap --args 64 -- firefox -p deck
deck       12208  3.2  3.0 11498632 460352 ?     Sl   22:12   0:03 /app/lib/firefox/firefox --name org.mozilla.firefox -p deck
deck       12632  0.9  0.2 219688 31232 ?        Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -parentBuildID 20240624183754 -prefsLen 35610 -prefMapSize 246302 -appDir /app/lib/firefox/browser {faefa3e3-204d-4fc3-bc47-59dfd22a3d0d} 2 true socket
deck       12663  9.8  0.9 10930704 138704 ?     Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -childID 1 -isForBrowser -prefsLen 35713 -prefMapSize 246302 -jsInitLen 234488 -parentBuildID 20240624183754 -greomni /app/lib/firefox/omni.ja -appomni /app/lib/firefox/browser/omni.ja -appDir /app/lib/firefox/browser {7c097d70-fd72-4043-a1ee-0185dd5e858a} 2 true tab
deck       12738 24.2  1.1 19475556 168408 ?     Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -childID 2 -isForBrowser -prefsLen 41254 -prefMapSize 246302 -jsInitLen 234488 -parentBuildID 20240624183754 -greomni /app/lib/firefox/omni.ja -appomni /app/lib/firefox/browser/omni.ja -appDir /app/lib/firefox/browser {d49e3af1-b98e-4ef9-a45b-40a8cd070b7c} 2 true tab
deck       12808  1.2  0.1 217876 29184 ?        Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -parentBuildID 20240624183754 -sandboxingKind 0 -prefsLen 41286 -prefMapSize 246302 -appDir /app/lib/firefox/browser {b760ed3e-d35d-48fa-ab04-a49b6989d413} 2 true utility
deck       12816  3.0  0.3 2413212 50632 ?       Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -childID 3 -isForBrowser -prefsLen 33210 -prefMapSize 246302 -jsInitLen 234488 -parentBuildID 20240624183754 -greomni /app/lib/firefox/omni.ja -appomni /app/lib/firefox/browser/omni.ja -appDir /app/lib/firefox/browser {0bfe04c7-d2af-4731-915c-89f016c1c094} 2 true tab
deck       12817  2.5  0.3 2413212 50692 ?       Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -childID 4 -isForBrowser -prefsLen 33210 -prefMapSize 246302 -jsInitLen 234488 -parentBuildID 20240624183754 -greomni /app/lib/firefox/omni.ja -appomni /app/lib/firefox/browser/omni.ja -appDir /app/lib/firefox/browser {eedc4570-ed41-42cc-bcfb-93d785bd354e} 2 true tab
deck       12858  2.7  0.3 2413212 50504 ?       Sl   22:14   0:00 /app/lib/firefox/firefox-bin -contentproc -childID 5 -isForBrowser -prefsLen 33267 -prefMapSize 246302 -jsInitLen 234488 -parentBuildID 20240624183754 -greomni /app/lib/firefox/omni.ja -appomni /app/lib/firefox/browser/omni.ja -appDir /app/lib/firefox/browser {a55c5b40-b8fb-4d1d-aa83-7d90b2d8b49d} 2 true tab
deck       12898  0.0  0.0   6500  2432 pts/1    S+   22:14   0:00 grep --color=auto firefox
(deck@SDOLED1T ~)$
```
- Non-steam games launched (greenlight) with pause on focus loss enabled, and automatically got paused by pause games
```
(deck@SDOLED1T ~)$ ps aux | grep greenlight
deck       13135  3.4  0.0  28108  5632 ?        S    22:15   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3111430402 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh io.github.unknownskl.greenlight --fullscreen
deck       13141  0.9  0.1 314728 21632 ?        Tl   22:15   0:00 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh io.github.unknownskl.greenlight --fullscreen
deck       13193  0.0  0.0   6500  2304 pts/1    S+   22:15   0:00 grep --color=auto greenlight
(deck@SDOLED1T ~)$
```
- After manually unpause non-steam games (greenlight)
```
(deck@SDOLED1T ~)$ ps aux | grep greenlight
deck       13135  0.3  0.0  28108  5632 ?        S    22:15   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3111430402 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh io.github.unknownskl.greenlight --fullscreen
deck       13402 11.4  1.0 1177928428 166144 ?   Sl   22:16   0:01 /app/main/greenlight --fullscreen
deck       13422  0.3  0.3 33794248 49024 ?      S    22:16   0:00 /app/main/greenlight --type=zygote --no-zygote-sandbox
deck       13428  0.6  0.0   2860  1792 ?        Ss   22:16   0:00 bwrap --args 46 -- /app/bin/zypak-helper child - /app/main/greenlight --type=zygote
deck       13438  0.2  0.0   2860  1152 ?        S    22:16   0:00 bwrap --args 46 -- /app/bin/zypak-helper child - /app/main/greenlight --type=zygote
deck       13440  0.3  0.3 33796888 50688 ?      S    22:16   0:00 /app/main/greenlight --type=zygote
deck       13462 30.1  1.3 34271512 202188 ?     Sl   22:16   0:03 /app/main/greenlight --type=gpu-process --enable-gpu-rasterization --enable-crash-reporter=... --user-data-dir=/home/deck/.var/app/io.github.unknownskl.greenlight/config/greenlight --gpu-preferences=... --shared-files --field-trial-handle=... --enable-features=CanvasOopRasterization,PlatformHEVCDecoderSupport,VaapiIgnoreDriverChecks,VaapiVideoDecoder,kWebSQLAccess --disable-features=SpareRendererForSitePerProcess --variations-seed-version
deck       13469  0.6  0.4 33868616 66720 ?      Sl   22:16   0:00 /app/main/greenlight --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --enable-crash-reporter=... --user-data-dir=/home/deck/.var/app/io.github.unknownskl.greenlight/config/greenlight --standard-schemes=app --secure-schemes=app --cors-schemes=app --fetch-schemes=app --service-worker-schemes=app --shared-files=v8_context_snapshot_data:100 --field-trial-handle=... --enable-features=CanvasOopRasterization,PlatformHEVCDecoderSupport,VaapiIgnoreDriverChecks,VaapiVideoDecoder,kWebSQLAccess --disable-features=SpareRendererForSitePerProcess --variations-seed-version
deck       13489 13.3  1.2 1186154428 184136 ?   Sl   22:16   0:01 /app/main/greenlight --type=renderer --enable-crash-reporter=... --user-data-dir=/home/deck/.var/app/io.github.unknownskl.greenlight/config/greenlight --standard-schemes=app --secure-schemes=app --cors-schemes=app --fetch-schemes=app --service-worker-schemes=app --app-path=/app/main/resources/app.asar --no-sandbox --no-zygote --enable-blink-features --first-renderer-process --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --time-ticks-at-unix-epoch=-1720446169037488 --launch-time-ticks=2028550417 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=... --enable-features=CanvasOopRasterization,PlatformHEVCDecoderSupport,VaapiIgnoreDriverChecks,VaapiVideoDecoder,kWebSQLAccess --disable-features=SpareRendererForSitePerProcess --variations-seed-version
deck       13579  0.0  0.0   6500  2304 pts/1    S+   22:16   0:00 grep --color=auto greenlight
(deck@SDOLED1T ~)$
```
- Non-steam games launched (GoG Galaxy) with pause on focus loss enabled, and automatically got paused by pause games
```
(deck@SDOLED1T ~)$ ps aux | grep Galaxy
deck       14642  1.1  0.0  28108  5632 ?        S    22:22   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3216372511 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       14654  0.4  0.0 261056  6772 ?        T    22:22   0:00 /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/pressure-vessel-wrap --env-if-host=PRESSURE_VESSEL_APP_LD_LIBRARY_PATH= --env-if-host=SYSTEM_PATH=/usr/local/bin:/usr/bin --env-if-host=STEAM_RUNTIME_LIBRARY_PATH=/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib32:/usr/lib/perf:/usr/lib:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/deck/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib --env-if-host=SYSTEM_LD_LIBRARY_PATH= --env-if-host=PATH=/usr/local/bin:/usr/bin --ld-preloads=:/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so --env-if-host=LD_PRELOAD=:/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so -- /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       14792  0.0  0.0   6500  2432 pts/1    S+   22:22   0:00 grep --color=auto Galaxy
(deck@SDOLED1T ~)$
```
- After manually unpause non-steam games (GoG Galaxy)
```
(deck@SDOLED1T ~)$ ps aux | grep Galaxy
deck       14642  0.2  0.0  28108  5632 ?        S    22:22   0:00 /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3216372511 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       14654  0.8  0.0   4608  1664 ?        S    22:22   0:00 /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/libexec/steam-runtime-tools-0/srt-bwrap --args 32 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 22 --regenerate-ld.so-cache /var/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --overrides-path /usr/lib/pressure-vessel/overrides --exit-with-parent --subreaper --assign-fd=1=6 --assign-fd=2=7 --shell=none --terminal=none --ld-preload=/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so --ld-preload=/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so -- /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       15030  0.1  0.0  26740  5376 ?        Ss   22:23   0:00 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 22 --regenerate-ld.so-cache /var/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --overrides-path /usr/lib/pressure-vessel/overrides --exit-with-parent --subreaper --assign-fd=1=6 --assign-fd=2=7 --shell=none --terminal=none --ld-preload=/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so --ld-preload=/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so -- /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       15056  0.7  0.1  50808 24788 ?        S    22:23   0:00 python3 /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton waitforexitandrun /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       15058  1.0  0.2 278476 37420 ?        Sl   22:23   0:00 c:\windows\system32\steam.exe /home/deck/.local/share/Steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
deck       15146 55.8  2.7 1969412 416644 ?      Rsl  22:23   0:15 C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe
deck       15155  2.1  0.4 1814920 72792 ?       Ssl  22:23   0:00 C:\Program Files (x86)\GOG Galaxy\GalaxyClientService.exe
deck       15250 18.0  1.8 2329876 276492 ?      Ssl  22:23   0:03 C:\Program Files (x86)\GOG Galaxy\GalaxyClient Helper.exe --type=gpu-process --field-trial-handle=... --disable-features=NetworkService --no-sandbox --log-file=C:\ProgramData\GOG.com\Galaxy\logs\cef.log --log-severity=info --user-agent=GOGGalaxyClient/2.0.74.352 (GOG Galaxy) 83b6745cff679691b69876bc7ee33e05e5d90bda (win10 x64) --lang=en-US --gpu-preferences=... --log-file=C:\ProgramData\GOG.com\Galaxy\logs\cef.log --service-request-channel-token=... --mojo-platform-channel-handle=1348 /prefetch:2
deck       15437  2.4  0.4 1804848 64900 ?       Ssl  22:23   0:00 C:\ProgramData\GOG.com\Galaxy\redists\GalaxyCommunication.exe
deck       15501 61.3  2.5 1945804 385272 ?      Ssl  22:23   0:07 C:\Program Files (x86)\GOG Galaxy\GalaxyClient Helper.exe --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --disable-threaded-scrolling --js-flags=--expose-gc --log-file=C:\ProgramData\GOG.com\Galaxy\logs\cef.log --field-trial-handle=... --disable-features=NetworkService --enable-blink-features=CSSBackdropFilter,AsyncClipboard --lang=en-US --log-file=C:\ProgramData\GOG.com\Galaxy\logs\cef.log --log-severity=info --user-agent=GOGGalaxyClient/2.0.74.352 (GOG Galaxy) 83b6745cff679691b69876bc7ee33e05e5d90bda (win10 x64) --disable-pdf-extension --disable-spell-checking --uncaught-exception-stack-size=999 --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=... --renderer-client-id=4 --mojo-platform-channel-handle=2588 /prefetch:1
deck       15505 12.1  1.8 1968028 278788 ?      Ssl  22:23   0:01 C:\Program Files (x86)\GOG Galaxy\GOG Galaxy Notifications Renderer.exe /waitUntilOtherInstanceCloses
deck       15756  0.0  0.0   6500  2304 pts/1    S+   22:24   0:00 grep --color=auto Galaxy
(deck@SDOLED1T ~)$
```

**Comment by AkazaRenn** [comment]
Thank you for merging it!

For the navigation issue, I agree with you but I don't know how to make that possible 😞 I may come back later once I have an idea on that.

As for the focus issue, I somewhat know where the problem is - Steam provides the app ID as `769` which is the same as the overlay for all non-Steam games, PLUS that this game has never been focused before paused, caused this problem. Solving it might cause some performance impact due to that Steam sends quite a few duplicate events for each focus change, and I think it might be better to ask them to fix it instead...

**Comment by wynn1212** [comment]
Hi @AkazaRenn,

You can try submit the bug report on https://github.com/ValveSoftware/steam-for-linux

**Comment by AkazaRenn** [comment]
@wynn1212 https://github.com/ValveSoftware/steam-for-linux/issues/11078
Hope they would check it.

**Comment by wynn1212** [comment]
Hi @AkazaRenn,

I also updated the document and screenshot, feel free to check it out.

**Comment by AkazaRenn** [comment]
FYI I have the API migration ready, we can start using it once Decky Loader v3 goes stable. https://github.com/AkazaRenn/SDH-PauseGames/pull/1

**Comment by wynn1212** [comment]
Hi @AkazaRenn, we can ready to ask @popsUlfr to take over and continue this project once we resolve the navigation problem.

As I'm trying to understand how the navigation is done by looking at this code:
- https://github.com/Alex4386/decky-terminal/blob/b2b6d708030920d0223d14632a6a1499d65e43a8/src/panel.tsx#L117-L156

I think we can look something with `Field` and `Focusable` first
- https://wiki.deckbrew.xyz/en/api-docs/decky-frontend-lib/deck/components/Field
- https://wiki.deckbrew.xyz/en/api-docs/decky-frontend-lib/deck/components/Focusable

**Comment by AkazaRenn** [comment]
@AkazaRenn sure I can give it a try this weekend!

**Pull request merged**
