### PR TITLE
Apply new decky API

### PR DESCRIPTION
**Pull request by AkazaRenn**
You can install it from this link https://github.com/AkazaRenn/SDH-PauseGames/releases/download/20240924192704/Pause.Games.zip
Please please test to make sure it fully works.

### CODE REVIEW

**Comment by wynn1212** [comment]
Sure, I'll test it later. 

I forgot to mention that I have a driving license test this week, so I won't be available. However, I'll try to test it as soon as possible.

**Comment by AkazaRenn** [comment]
@wynn1212 no worries, good luck on the test

**Review by wynn1212 — APPROVED** [review]
LGTM, will start testing soon.

**Comment by wynn1212** [comment]
- [ ] Testing on SteamOS Stable Branches + SteamOS Stable Client + Decky Loader Stable
  - SteamOS: 3.5.19 20240422.1
  - Steam Client: 1726683985
  - Decky Loader: v3.0.1
- [ ] Testing on SteamOS Preview Branches + SteamOS Beta Client + Decky Loader Preview
- [ ] Testing on SteamOS Main Branches + SteamOS Beta Client + Decky Loader Preview

**Comment by wynn1212** [comment]
Testing seems be no problem.

**Comment by wynn1212** [comment]
Hi @AkazaRenn, 
The release preparation for v1.0.0 is complete, and I'm ready to submit the pull request to the decky-plugin-database.

Here is the changelog since v0.4.3:

***

Update SDH-PauseGames to v1.0.0 with the following fixes and new features:

- Pause/Resume button is now located on the game icon.
- Migrate settings to json-based.
- https://github.com/popsUlfr/SDH-PauseGames/issues/13 Clear `stickyPause` state on manual resume.
- https://github.com/popsUlfr/SDH-PauseGames/issues/22 Add `noAutoPauseSet` to select which game shouldn't be paused when on focus loss; this can be toggled on the right side of the Pause Games list.
- https://github.com/popsUlfr/SDH-PauseGames/issues/19 Patch `SteamClient.Apps.TerminateApp()` to un-pause games on exit.
- Migrate to Decky V3.

***
If I missed anything in this changelog, please let me know so I can update it.

Thanks again!

**Comment by wynn1212** [comment]
Submitted! You can take a look at it here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/716 .

If anything goes wrong, we'll need to fix it to ensure this release goes live.

**Pull request merged**
